import { fix_position } from "svelte/internal"
const foodItems = [
	{ name: "Mandarin", desc: "5 Mandarin", src: "./Mandarin.jpg",  num: 2 },
	{ name: "Orange", desc: "5 Oranges", src: "./Orange.jpg", num: 2 },
	{ name: "Flour", desc: "1 cup", src: "./cupflour.jpg", num: 1 },
	{ name: "Milo", desc: "Small Container", num: 9 },
	{ name: "Coffee", desc: "Small Container", num: 9 },
	{ name: "Tea Bags", desc: "", num: 9 },
	{ name: "Orange Juice", desc: "", num: 4 },
	{ name: "Cranberry Juice", desc: "", num: 4 },
	{ name: "Strawberry Jam", desc: "", num: 4 },
	{ name: "Raspberry Jam", desc: "", num: 4 },
	{ name: "Apricot Jam", desc: "", num: 4 },
	{ name: "Marmalade", desc: "", num: 4 },
	{ name: "Marmite", desc: "", num: 6 },
	{ name: "Vegemite", desc: "", num: 6 },
	{ name: "Peanut Butter Smooth", desc: "Smooth", num: 3 },
	{ name: "Peanut Butter Crunchy", desc: "Crunchy", num: 3 },
	{ name: "Honey", desc: "", num: 7 },
	{ name: "Butter", desc: "", num: 4 },
	{ name: "Margarine", desc: "", num: 4 },
	{ name: "Cheese", desc: "Half Block", num: 5 },
	{ name: "Yoghurt", desc: "", num: 4 },
	{ name: "Plain Biscuits", desc: "", num: 1 },
	{ name: "Chocolate Biscuits", desc: "", num: 3 },
	{ name: "Crackers", desc: "", num: 2 },
	{ name: "Eggs", desc: "", num: 2 },
	{ name: "Cornflakes", desc: "", num: 4 },
	{ name: "Weetbix", desc: "", num: 7 },
	{ name: "Muesli", desc: "", num: 6 },
	{ name: "Rice Bubles", desc: "", num: 4 },
	{ name: "Just Right", desc: "", num: 6 },
	{ name: "Porridge", desc: "", num: 2 },
	{ name: "Pears", desc: "", num: 1 },
	{ name: "Peaches", desc: "", num: 1 },
	{ name: "Apricots", desc: "", num: 1 },
	{ name: "Fruit Salad", desc: "", num: 1 },
	{ name: "Creamed Corn", desc: "", num: 1 },
	{ name: "Tomato Relish", desc: "", num: 3 },
	{ name: "Tomato Sauce", desc: "", num: 5 },
	{ name: "Pasta Sauce", desc: "", num: 3 },
	{ name: "Pasta", desc: "", num: 1 },
	{ name: "Spaghetti", desc: "", num: 1 },
	{ name: "Rice", desc: "", num: 2 },
	{ name: "White Sugar", desc: "", num: 2 },
	{ name: "Brown Sugar", desc: "", num: 3 },
	{ name: "Baking Powder", desc: "", num: 1 },
	{ name: "Baking Soda", desc: "", num: 1 },
	{ name: "Cocoa", desc: "", num: 5 },
	{ name: "Icing Sugar", desc: "", num: 2 },
	{ name: "Condensed Milk", desc: "", num: 2 },
	{ name: "Vanilla Essence", desc: "", num: 1 },
	{ name: "Spray and Wipe", desc: "", num: 4 },
	{ name: "Dishwashing Liquid", desc: "", num: 4 },
	{ name: "Dishwashing Powder", desc: "", num: 7 },
	{ name: "Dish Cloths", desc: "", num: 1 },
	{ name: "Glad Wrao", desc: "", num: 3 },
	{ name: "Tin Foil", desc: "", num: 3 },
	{ name: "White Bread", desc: "", num: 2 },
	{ name: "Brown Bread", desc: "", num: 3 },
	{ name: "Green Milk", desc: "", num: 4 },
	{ name: "Blue Milk", desc: "", num: 5 },
	{ name: "Baked Beans", desc: "", num: 1 },
]
export default foodItems
